# Generated by Django 4.2.1 on 2023-06-02 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=200, unique=True)),
                ('Product_Name', models.CharField(max_length=50, unique=True)),
                ('Lost_on', models.DateField(auto_now_add=True)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
                ('Name_and_Roll_no_of_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_Lost_Object', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Lost_on'],
            },
        ),
    ]
