# Generated by Django 4.2.1 on 2023-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost_object',
            name='Status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=10),
        ),
    ]
