# Generated by Django 4.2.1 on 2023-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lost_object_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost_object',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
